// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoOZ3-9A9_sLWrKPTTtgkEkwcDsVb05fQ',
    appId: '1:606204502038:web:3348f0b6259a2a36c89537',
    messagingSenderId: '606204502038',
    projectId: 'travelapp-93d6d',
    authDomain: 'travelapp-93d6d.firebaseapp.com',
    storageBucket: 'travelapp-93d6d.appspot.com',
    measurementId: 'G-YM9X4E9YM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8WFlF6yAz94cVhSuz_w81WGfsr_B5zEE',
    appId: '1:606204502038:android:0783f7e394fada93c89537',
    messagingSenderId: '606204502038',
    projectId: 'travelapp-93d6d',
    storageBucket: 'travelapp-93d6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClJn-4z2RCU0yFxbzFG_gdzCksy0E9SfM',
    appId: '1:606204502038:ios:b162f592f3d559e5c89537',
    messagingSenderId: '606204502038',
    projectId: 'travelapp-93d6d',
    storageBucket: 'travelapp-93d6d.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );
}
